"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
auto_upgrade = false
console_title_template = '{{ .Folder }}'
version = 2

[palette]
gray = '#808080'
green = '#228B22'
light-green = '#82BA93'
pink1 = '#F9D1E3'
pink2 = '#F4AEC8'
pink3 = '#F092B5'
pink4 = '#EC77A3'
pink5 = '#E36A8D'
pink6 = '#E85C90'
red = '#FF6666'
white = '#FFFFFF'

[var]
good_emojis = [
    "🥹",
    "😇",
    "😉",
    "😌",
    "🥰",
    "😍",
    "😋",
    "😘",
    "🤪",
    "🥳",
    "🤩",
    "🤓",
    "😎",
    "🥸",
    "🤯",
    "🤗",
    "😱",
    "🫡",
    "🫨",
    "🤠",
    "👏",
    "🙏",
    "🎉"
]
bad_emojis = [
    "😆",
    "😂",
    "😔",
    "😭",
    "😳",
    "🤬",
    "😡",
    "🫢",
    "😑",
    "😬",
    "👹",
    "😰",
    "😟",
    "😞",
    "🤫",
    "🫣",
    "🤡",
    "💀",
    "😵",
    "👎",
    "😅",
    "🥲",
    "🙃",
    "🤨",
    "🧐",
    "😕",
    "😒",
    "🙁",
    "🤔",
    "🫠",
    "😐",
    "🤥",
    "🙄",
    "🥴",
    "😳",
    "👀",
    "🥱",
    "😮"
]


######## main prompt ###########################################################

[[blocks]]
alignment = 'left'
newline = false
type = 'prompt'

# os
[[blocks.segments]]
type = 'os'
foreground = 'black'
background = 'p:pink1'
style = 'powerline'
leading_powerline_symbol = ''
powerline_symbol = ''
template = '{{ if ne .Icon "" }}{{ .Icon }} {{end}}'

# user/ host
[[blocks.segments]]
type = 'session'
background = 'p:pink2'
foreground = 'black'
style = 'powerline'
powerline_symbol = ' '
leading_powerline_symbol = ''
template = "{{if .SSHSession }}{{ .UserName }} 󰴽{{ .HostName }} {{end}}"
# template = "{{ .UserName }} 󰴽{{ .HostName }}" # uncomment to show user and host all the time

# Path
[[blocks.segments]]
type = 'path'
foreground = 'black'
background = "p:pink3"
alias = 'path_seg'
powerline_symbol = ' '
leading_powerline_symbol = ''
style = 'powerline'
template = '{{ .Path }}'

[blocks.segments.properties]
style = 'agnoster_full'
home_icon = ' '

[blocks.segments.properties.mapped_locations]
"/" = ' '
"~/Library/Mobile Documents/com~apple~CloudDocs" = ' /Library/ '
"~/Library/Mobile Documents/iCloud~md~obsidian/Documents" = ' /Library/ '


# Git
[[blocks.segments]]
foreground = 'black'
background = 'p:pink5'
style = 'powerline'
powerline_symbol = ''
template = ' {{ .HEAD }}{{if lt (add .Ahead .Behind) 1}}<p:light-pink> </>{{end}}{{if gt .Working.Unmerged 0}}  {{.Working.Unmerged}}{{end}}{{if gt .Ahead 0}} {{.Ahead}}{{end}}{{if gt .Behind 0}}{{.Behind}}{{end}}{{ if (or .Working.Added .Working.Modified .Working.Deleted) }}  {{ add .Working.Added .Working.Modified .Working.Deleted }}{{end}}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}<p:gray> 󱠷 {{ .StashCount }}</>{{ end }}'
type = 'git'

[blocks.segments.properties]
branch_icon = ' '
# fetch_stash_count = true
# fetch_status = false
# # fetch_upstream_icon = false
# fetch_worktree_count = true



####### right prompt ###########################################################

[[blocks]]
alignment = 'right'
# newline = true
type = 'prompt'


# execution time and emojis
[[blocks.segments]]
type = 'executiontime'
alias = 'exec_time'
style = 'powerline'
leading_powerline_symbol = ''
powerline_symbol = ''
background = 'p:gray'
foreground = 'black'
background_templates = ['{{if ne .Code 0}}p:red{{end}}']
templates = [
    '{{ .FormattedMs }}',
    '{{$e := ""}}{{if ne .Code 0}}{{ $e = random .Var.bad_emojis }}{{else}}{{ $e = random .Var.good_emojis }}{{end}} {{ $e }}{{ $e }}{{ $e }} ',
]

[blocks.segments.properties]
style = 'austin'
threshold = 0.0


##### Second line ###########################################################

[[blocks]]
alignment = 'left'
newline = true
type = 'prompt'

[[blocks.segments]]
foreground = 'p:pink5'
style = 'plain'
template = '   '
type = 'text'


##### transient prompt ###########################################################

[transient_prompt]
foreground = 'p:pink3'
template = '{{ .Segments.path_seg.Path }}<p:pink5>   '
